############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
  namespace: pihole
type: Opaque
data:
  WEBPASSWORD: Uk9PVDEyMzQ1Njc4OQ== # ROOT123456789
---