############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 24/11/2024        #
############################
---
apiVersion: v1
kind: Secret
metadata:
  name: nicehash-secret
  namespace: nicehash
type: Opaque
data:
  MINING_ADDRESS: TkhiWmtoMWsxbXI4c1BZMjd6bVdwMjkxRmZ1ekdpd05STXNl # NHbZkh1k1mr8sPY27zmWp291FfuzGiwNRMse
---